"""update user

Revision ID: 06b4b39a8101
Revises: ea0d371294b3
Create Date: 2026-07-08 21:38:49.963667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b4b39a8101'
down_revision: Union[str, Sequence[str], None] = 'ea0d371294b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OTP',
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('OTPString', sa.String(), nullable=False),
    sa.Column('ExpiresAt', sa.DateTime(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('Attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('Email')
    )
    op.create_table('RefreshToken',
    sa.Column('ID', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RefreshToken')
    op.drop_table('OTP')
    # ### end Alembic commands ###
