"""Add user_id to TaskReminder

Revision ID: 099e84f48a77
Revises: 0fc49f113563
Create Date: 2026-07-24 02:19:36.793482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099e84f48a77'
down_revision: Union[str, Sequence[str], None] = '0fc49f113563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TaskReminder', sa.Column('user_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_TaskReminder_user_id'), 'TaskReminder', ['user_id'], unique=False)
    op.create_unique_constraint('uq_task_user_reminder', 'TaskReminder', ['task_id', 'user_id'])
    op.create_foreign_key(None, 'TaskReminder', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TaskReminder', type_='foreignkey')
    op.drop_constraint('uq_task_user_reminder', 'TaskReminder', type_='unique')
    op.drop_index(op.f('ix_TaskReminder_user_id'), table_name='TaskReminder')
    op.drop_column('TaskReminder', 'user_id')
    # ### end Alembic commands ###
