"""add roles enum

Revision ID: 0d7e2dde5f5f
Revises: 
Create Date: 2026-07-10 14:47:20.996645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d7e2dde5f5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


roles_enum = sa.Enum("Admin", "admin", "Member", name="roles")

def upgrade():
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    roles_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('RefreshToken',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expire_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.alter_column(
    "User",
    "role",
    existing_type=sa.VARCHAR(),
    type_=roles_enum,
    existing_nullable=False,
    postgresql_using="role::roles",
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'role',
               existing_type=sa.Enum('Admin', 'admin', 'Member', name='roles'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('RefreshToken')
    # ### end Alembic commands ###
