"""Add TaskReminder table

Revision ID: 0fc49f113563
Revises: aff6e9b34aa7
Create Date: 2026-07-24 01:48:31.089156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc49f113563'
down_revision: Union[str, Sequence[str], None] = 'aff6e9b34aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TaskReminder',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('interval_value', sa.Integer(), nullable=False),
    sa.Column('interval_unit', sa.String(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['Task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TaskReminder_next_run_at'), 'TaskReminder', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_TaskReminder_task_id'), 'TaskReminder', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TaskReminder_task_id'), table_name='TaskReminder')
    op.drop_index(op.f('ix_TaskReminder_next_run_at'), table_name='TaskReminder')
    op.drop_table('TaskReminder')
    # ### end Alembic commands ###
