"""Add Notification table

Revision ID: 14492933fb97
Revises: e0c6cdd2b938
Create Date: 2026-07-20 01:46:06.922207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14492933fb97'
down_revision: Union[str, Sequence[str], None] = 'e0c6cdd2b938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Notification',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('related_task_id', sa.String(), nullable=True),
    sa.Column('related_comment_id', sa.String(), nullable=True),
    sa.Column('related_project_id', sa.String(), nullable=True),
    sa.Column('related_message_id', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('delivered', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['related_message_id'], ['Message.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_project_id'], ['Project.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_task_id'], ['Task.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Notification')
    # ### end Alembic commands ###
