"""Fixed Import Error

Revision ID: 32e65e9a6e86
Revises: 02ae2f72f09a
Create Date: 2026-07-15 21:00:30.775272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e65e9a6e86'
down_revision: Union[str, Sequence[str], None] = '02ae2f72f09a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Project',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('soft_delete', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('category', sa.Enum('upwork', 'US_based', 'Pak_profile', 'inhouse', name='categories'), nullable=False),
    sa.Column('status', sa.Enum('planned', 'started', 'in_progress', 'finished', 'under_review', 'archived', name='projectstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tag',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ProjectTag',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['Project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['Tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'tag_id')
    )
    op.create_table('Task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schedule_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'started', 'in_progress', 'finished', 'under_review', 'archived', name='projectstatus'), nullable=False),
    sa.Column('soft_delete', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='levels'), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['Project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_dependency',
    sa.Column('prerequisite_task_id', sa.String(), nullable=False),
    sa.Column('dependant_task_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dependant_task_id'], ['Task.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_task_id'], ['Task.id'], ),
    sa.PrimaryKeyConstraint('prerequisite_task_id', 'dependant_task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_dependency')
    op.drop_table('Task')
    op.drop_table('ProjectTag')
    op.drop_table('Tag')
    op.drop_table('Project')
    # ### end Alembic commands ###
