"""Modification to project table

Revision ID: 330a04224237
Revises: c3e29926db77
Create Date: 2026-07-19 04:12:29.908948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '330a04224237'
down_revision: Union[str, Sequence[str], None] = 'c3e29926db77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Project_team_id_key'), 'Project', type_='unique')
    op.drop_constraint(op.f('Project_team_id_fkey'), 'Project', type_='foreignkey')
    op.drop_column('Project', 'team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Project', sa.Column('team_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('Project_team_id_fkey'), 'Project', 'Project', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('Project_team_id_key'), 'Project', ['team_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
