"""Project Name Unique Constraint

Revision ID: 617473f46a39
Revises: b8f29d83bcdf
Create Date: 2026-07-16 19:34:22.782428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617473f46a39'
down_revision: Union[str, Sequence[str], None] = 'b8f29d83bcdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Project', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Project', type_='unique')
    # ### end Alembic commands ###
