"""Add is_external flag to User

Revision ID: 6e67cd5b8de9
Revises: a6344eae818b
Create Date: 2026-07-21 23:09:03.781220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e67cd5b8de9'
down_revision: Union[str, Sequence[str], None] = 'a6344eae818b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_external', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_external')
    # ### end Alembic commands ###
