"""OTP Update

Revision ID: 7077a9083346
Revises: 2629341e0d63
Create Date: 2026-07-17 03:43:13.191553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7077a9083346'
down_revision: Union[str, Sequence[str], None] = '2629341e0d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'role',
               existing_type=postgresql.ENUM('Admin', 'admin', 'Member', name='roles'),
               type_=sa.Enum('admin', 'member', name='userroles'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'role',
               existing_type=sa.Enum('admin', 'member', name='userroles'),
               type_=postgresql.ENUM('Admin', 'admin', 'Member', name='roles'),
               existing_nullable=False)
    # ### end Alembic commands ###
