"""remove project_id from assignment

Revision ID: 7739adbc2ec5
Revises: f5d2b0b9b346
Create Date: 2026-07-20 10:51:14.761319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7739adbc2ec5'
down_revision: Union[str, Sequence[str], None] = 'f5d2b0b9b346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Assignment_project_id_fkey'), 'Assignment', type_='foreignkey')
    op.drop_column('Assignment', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Assignment', sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('Assignment_project_id_fkey'), 'Assignment', 'Project', ['project_id'], ['id'])
    # ### end Alembic commands ###
