"""add create_tag to ActivityActionType

Revision ID: 8357c8a0b8b8
Revises: 7739adbc2ec5
Create Date: 2026-07-20 11:52:33.648666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8357c8a0b8b8'
down_revision: Union[str, Sequence[str], None] = '7739adbc2ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
