"""Add due date to Task

Revision ID: a6344eae818b
Revises: 6da1769b3ffd
Create Date: 2026-07-21 22:30:45.381912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6344eae818b'
down_revision: Union[str, Sequence[str], None] = '6da1769b3ffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Task', sa.Column('due_date', sa.Date(), nullable=True))
    op.create_unique_constraint('uq_teammember_user_team', 'TeamMember', ['user_id', 'team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_teammember_user_team', 'TeamMember', type_='unique')
    op.drop_column('Task', 'due_date')
    # ### end Alembic commands ###
