"""add_due_reminder_sent_to_task

Revision ID: aff6e9b34aa7
Revises: ed4774a55b61
Create Date: 2026-07-23 01:46:44.730183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aff6e9b34aa7'
down_revision: Union[str, Sequence[str], None] = 'ed4774a55b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Task', sa.Column('due_reminder_sent', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Task', 'due_reminder_sent')
    # ### end Alembic commands ###
