"""Assignment Update

Revision ID: b8f29d83bcdf
Revises: 32e65e9a6e86
Create Date: 2026-07-16 00:50:20.930587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f29d83bcdf'
down_revision: Union[str, Sequence[str], None] = '32e65e9a6e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    assignment_role = sa.Enum(
            "team_lead",
            "manager",
            "developer",
            name="assignmentrole",
            create_type=False,
        )


    op.create_table(
        "Assignment",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("role", assignment_role, nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["Project.id"]),
        sa.ForeignKeyConstraint(["task_id"], ["Task.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["User.id"]),
        sa.PrimaryKeyConstraint("id"),
    )    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Assignment')
    # ### end Alembic commands ###
