"""User and Notification

Revision ID: c0b579b4fc5c
Revises: 598ee487040c
Create Date: 2026-07-09 01:46:33.853011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0b579b4fc5c'
down_revision: Union[str, Sequence[str], None] = '598ee487040c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RefreshToken')
    op.drop_table('OTP')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OTP',
    sa.Column('Email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('OTPString', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ExpiresAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('CreatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('Attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Email', name=op.f('OTP_pkey'))
    )
    op.create_table('RefreshToken',
    sa.Column('ID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID', name=op.f('RefreshToken_pkey'))
    )
    # ### end Alembic commands ###
