"""Modification to project table

Revision ID: c3e29926db77
Revises: f3a8be4e00cf
Create Date: 2026-07-19 03:12:32.210524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3e29926db77'
down_revision: Union[str, Sequence[str], None] = 'f3a8be4e00cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Project', sa.Column('team_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'Project', ['team_id'])
    op.create_foreign_key(None, 'Project', 'Project', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Project', type_='foreignkey')
    op.drop_constraint(None, 'Project', type_='unique')
    op.drop_column('Project', 'team_id')
    # ### end Alembic commands ###
