"""Refresh token format

Revision ID: eb90bf260bc1
Revises: e5fa29b0e6ce
Create Date: 2026-07-13 04:03:51.927215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb90bf260bc1'
down_revision: Union[str, Sequence[str], None] = 'e5fa29b0e6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RefreshToken', sa.Column('id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RefreshToken', 'id')
    op.create_table('RefreshTokenTable',
    sa.Column('ID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID', name=op.f('RefreshTokenTable_pkey'))
    )
    # ### end Alembic commands ###
