"""add activity_log table

Revision ID: f5d2b0b9b346
Revises: 97d730f7d72d
Create Date: 2026-07-20 03:42:17.959528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d2b0b9b346'
down_revision: Union[str, Sequence[str], None] = '97d730f7d72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ActivityLog',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('modified_by_user_id', sa.String(), nullable=False),
    sa.Column('target_user_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.Enum('create_project', 'update_project', 'archive_project', 'delete_project', 'create_task', 'update_task', 'delete_task', 'add_prerequisite', 'create_user', 'update_user', 'delete_user', 'modify_user_status', 'change_user_privacy', 'assign_user', name='activityactiontype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('change_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['modified_by_user_id'], ['User.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['Project.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['User.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['Task.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ActivityLog')
    # ### end Alembic commands ###
