"""added Levels Enum

Revision ID: fb37afded1a2
Revises: 82fb122bc2fe
Create Date: 2026-07-13 19:27:20.551141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb37afded1a2'
down_revision: Union[str, Sequence[str], None] = '82fb122bc2fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

levels_enum = sa.Enum(
    "low",
    "medium",
    "high",
    name="Levels",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    levels_enum.create(op.get_bind(), checkfirst=True)

    # Add the column
    op.add_column(
        "User",
        sa.Column(
            "privacy_level",
            levels_enum,
            nullable=False,
            server_default="medium",  # or "low"/"high" as appropriate
        ),
    )    
    op.drop_column('User', 'privacyLevel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('privacyLevel', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('User', 'privacy_level')
    op.create_table('Message',
    sa.Column('ID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('MemberID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('TeamID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['MemberID'], ['TeamMembers.ID'], name=op.f('Message_MemberID_fkey')),
    sa.ForeignKeyConstraint(['TeamID'], ['Team.ID'], name=op.f('Message_TeamID_fkey')),
    sa.PrimaryKeyConstraint('ID', name=op.f('Message_pkey'))
    )
    op.create_table('RefreshTokenTable',
    sa.Column('ID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID', name=op.f('RefreshTokenTable_pkey'))
    )
    op.create_table('OTPTable',
    sa.Column('Email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('OTPString', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ExpiresAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('CreatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('Attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Email', name=op.f('OTPTable_pkey'))
    )
    op.create_table('Comment',
    sa.Column('ID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('TaskID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('UserID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ReplyID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ReplyID'], ['Comment.ID'], name=op.f('Comment_ReplyID_fkey')),
    sa.ForeignKeyConstraint(['TaskID'], ['Task.ID'], name=op.f('Comment_TaskID_fkey')),
    sa.ForeignKeyConstraint(['UserID'], ['User.id'], name=op.f('Comment_UserID_fkey')),
    sa.PrimaryKeyConstraint('ID', name=op.f('Comment_pkey'))
    )
    op.create_table('ActivityLog',
    sa.Column('ID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ModifiedByUserID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('TargetUserID', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('TaskID', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ProjectID', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ActionType', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ActionTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ModifiedByUserID'], ['User.id'], name=op.f('ActivityLog_ModifiedByUserID_fkey')),
    sa.ForeignKeyConstraint(['ProjectID'], ['Project.ID'], name=op.f('ActivityLog_ProjectID_fkey')),
    sa.ForeignKeyConstraint(['TargetUserID'], ['User.id'], name=op.f('ActivityLog_TargetUserID_fkey')),
    sa.ForeignKeyConstraint(['TaskID'], ['Task.ID'], name=op.f('ActivityLog_TaskID_fkey')),
    sa.PrimaryKeyConstraint('ID', name=op.f('ActivityLog_pkey'))
    )
    op.create_table('TaskDepends',
    sa.Column('ParentTask', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ChildTask', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ChildTask'], ['Task.ID'], name=op.f('TaskDepends_ChildTask_fkey')),
    sa.ForeignKeyConstraint(['ParentTask'], ['Task.ID'], name=op.f('TaskDepends_ParentTask_fkey')),
    sa.PrimaryKeyConstraint('ParentTask', 'ChildTask', name=op.f('TaskDepends_pkey'))
    )
    op.create_table('ExternalCollaboration',
    sa.Column('ID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ProjectID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('TaskID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Purpose', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('AccessType', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ProjectID'], ['Project.ID'], name=op.f('ExternalCollaboration_ProjectID_fkey')),
    sa.ForeignKeyConstraint(['TaskID'], ['Task.ID'], name=op.f('ExternalCollaboration_TaskID_fkey')),
    sa.PrimaryKeyConstraint('ID', name=op.f('ExternalCollaboration_pkey'))
    )
    op.create_table('Task',
    sa.Column('ID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('projectID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ScheduleDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('SoftDelete', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('Priority', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['projectID'], ['Project.ID'], name=op.f('Task_projectID_fkey')),
    sa.PrimaryKeyConstraint('ID', name=op.f('Task_pkey'))
    )
    op.create_table('Team',
    sa.Column('ID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ProjectID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ReadAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ProjectID'], ['Project.ID'], name=op.f('Team_ProjectID_fkey')),
    sa.PrimaryKeyConstraint('ID', name=op.f('Team_pkey'))
    )
    op.create_table('Project',
    sa.Column('ID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Archived', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('StartDate', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('EndDate', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('SoftDelete', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('Tag', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Categories', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID', name=op.f('Project_pkey'))
    )
    op.create_table('Notification',
    sa.Column('ID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('UserID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Subject', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Schedule', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('Read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ReadAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('RelatedTask', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('RelatedComment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('RelatedProject', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('RelatedMessage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['RelatedComment'], ['Comment.ID'], name=op.f('Notification_RelatedComment_fkey')),
    sa.ForeignKeyConstraint(['RelatedMessage'], ['Message.ID'], name=op.f('Notification_RelatedMessage_fkey')),
    sa.ForeignKeyConstraint(['RelatedProject'], ['Project.ID'], name=op.f('Notification_RelatedProject_fkey')),
    sa.ForeignKeyConstraint(['RelatedTask'], ['Task.ID'], name=op.f('Notification_RelatedTask_fkey')),
    sa.ForeignKeyConstraint(['UserID'], ['User.id'], name=op.f('Notification_UserID_fkey')),
    sa.PrimaryKeyConstraint('ID', name=op.f('Notification_pkey'))
    )
    op.create_table('TeamMembers',
    sa.Column('ID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('UserID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('TeamID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['TeamID'], ['Team.ID'], name=op.f('TeamMembers_TeamID_fkey')),
    sa.ForeignKeyConstraint(['UserID'], ['User.id'], name=op.f('TeamMembers_UserID_fkey')),
    sa.PrimaryKeyConstraint('ID', name=op.f('TeamMembers_pkey'))
    )
    op.create_table('Assignment',
    sa.Column('ID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('UserID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ProjectID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('TaskID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ProjectID'], ['Project.ID'], name=op.f('Assignment_ProjectID_fkey')),
    sa.ForeignKeyConstraint(['TaskID'], ['Task.ID'], name=op.f('Assignment_TaskID_fkey')),
    sa.ForeignKeyConstraint(['UserID'], ['User.id'], name=op.f('Assignment_UserID_fkey')),
    sa.PrimaryKeyConstraint('ID', name=op.f('Assignment_pkey'))
    )
    # ### end Alembic commands ###
